<?xml version="1.0" encoding="utf-8"?>
<Database Name="BAMPrimaryImport" Class="TrackingActivityContext" AccessModifier="Internal" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.bam_Process_AllInstances" Member="Processes">
    <Type Name="Process">
      <Column Name="ActivityID" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BeginTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="InterchangeID" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="ProcessName" Member="Name" Storage="_ProcessName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(9)" CanBeNull="true" />
      <Column Name="Value1" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="Value2" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="Value3" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Association Name="Process_ProcessingStep" Member="ProcessingSteps" ThisKey="ActivityID" OtherKey="ProcessActivityID" Type="ProcessingStep" />
      <Association Name="Process_ProcessMessagingStep" Member="ProcessMessagingSteps" ThisKey="ActivityID" OtherKey="ProcessActivityID" Type="ProcessMessagingStep" />
    </Type>
  </Table>
  <Table Name="dbo.bam_ProcessingStep_AllInstances" Member="ProcessingSteps">
    <Type Name="ProcessingStep">
      <Column Name="ActivityID" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BeginTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ErrorDescription" Type="System.String" DbType="NVarChar(2048)" CanBeNull="true" />
      <Column Name="MachineName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ProcessActivityID" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(9)" CanBeNull="true" />
      <Column Name="StepName" Member="Name" Storage="_StepName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Association Name="Process_ProcessingStep" Member="Process" ThisKey="ProcessActivityID" OtherKey="ActivityID" Type="Process" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.bam_ProcessMessagingStep_AllInstances" Member="ProcessMessagingSteps">
    <Type Name="ProcessMessagingStep">
      <Column Name="ActivityID" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="MessagingStepActivityID" Type="System.String" DbType="NVarChar(128)" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MessagingStepStatus" Type="System.String" DbType="NVarChar(13)" CanBeNull="true" />
      <Column Name="ProcessActivityID" Type="System.String" DbType="NVarChar(128)" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Process_ProcessMessagingStep" Member="Process" ThisKey="ProcessActivityID" OtherKey="ActivityID" Type="Process" IsForeignKey="true" />
      <Association Name="MessagingStep_ProcessMessagingStep" Member="MessagingStep" ThisKey="MessagingStepActivityID" OtherKey="ActivityID" Type="MessagingStep" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.bam_MessagingStep_AllInstances" Member="MessagingSteps">
    <Type Name="MessagingStep">
      <Column Name="ActivityID" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ErrorCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ErrorDescription" Type="System.String" DbType="NVarChar(2048)" CanBeNull="true" />
      <Column Name="InterchangeID" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="MachineName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="MessageID" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="MessageSize" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MessageType" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PortName" Member="Name" Storage="_PortName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="RetryCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(13)" CanBeNull="true" />
      <Column Name="Time" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TransportLocation" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="TransportType" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Value1" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="Value2" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="Value3" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Association Name="MessagingStep_ProcessMessagingStep" Member="ProcessMessagingSteps" ThisKey="ActivityID" OtherKey="MessagingStepActivityID" Type="ProcessMessagingStep" />
      <Association Name="MessagingStep_Context" Member="Context" Storage="_Contexts" ThisKey="ActivityID" OtherKey="MessagingStepActivityID" Type="Context" Cardinality="One" />
      <Association Name="MessagingStep_Message" Member="Message" Storage="_Messages" ThisKey="ActivityID" OtherKey="MessagingStepActivityID" Type="Message" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.vw_MessagingStepContexts" Member="Contexts">
    <Type Name="Context">
      <Column Name="MessagingStepActivityID" Type="System.String" DbType="NVarChar(128)" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EncodedContext" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="MessagingStep_Context" Member="MessagingStep" ThisKey="MessagingStepActivityID" OtherKey="ActivityID" Type="MessagingStep" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_MessagingStepMessages" Member="Messages">
    <Type Name="Message">
      <Column Name="MessagingStepActivityID" Type="System.String" DbType="NVarChar(128)" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EncodedBodyType" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="EncodedBody" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="MessagingStep_Message" Member="MessagingStep" ThisKey="MessagingStepActivityID" OtherKey="ActivityID" Type="MessagingStep" IsForeignKey="true" />
    </Type>
  </Table>
</Database>