//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Be.Stateless.BizTalk.Orchestrations.Dummy
{
	using System;
	using System.CodeDom.Compiler;
	using Be.Stateless.BizTalk.Dsl.Binding;
	using Microsoft.XLANGs.Core;
	using Be.Stateless.BizTalk.Orchestrations.Dummy;
	
	
	[GeneratedCodeAttribute("Be.Stateless.BizTalk.Dsl", "1.0.0.0")]
	internal partial interface IProcessOrchestrationBinding : IOrchestrationBinding
	{
		
		ISendPort SendPort
		{
			get;
			set;
		}
		
		IReceivePort ReceivePort
		{
			get;
			set;
		}
		
		IReceivePort RequestResponsePort
		{
			get;
			set;
		}
		
		ISendPort SolicitResponsePort
		{
			get;
			set;
		}
	}
	
	[GeneratedCodeAttribute("Be.Stateless.BizTalk.Dsl", "1.0.0.0")]
	internal partial class ProcessOrchestrationBinding : OrchestrationBindingBase<Process>, IProcessOrchestrationBinding
	{
		
		#region Nested Type: SendPort
		public struct SendPort
		{
			
			public struct Operations
			{
				
				public struct SendOperation
				{
					
					public static string Name = "SendOperation";
				}
			}
		}
		#endregion
		
		#region Nested Type: ReceivePort
		public struct ReceivePort
		{
			
			public struct Operations
			{
				
				public struct ReceiveOperation
				{
					
					public static string Name = "ReceiveOperation";
				}
			}
		}
		#endregion
		
		#region Nested Type: RequestResponsePort
		public struct RequestResponsePort
		{
			
			public struct Operations
			{
				
				public struct RequestResponseOperation
				{
					
					public static string Name = "RequestResponseOperation";
				}
			}
		}
		#endregion
		
		#region Nested Type: SolicitResponsePort
		public struct SolicitResponsePort
		{
			
			public struct Operations
			{
				
				public struct SolicitResponseOperation
				{
					
					public static string Name = "SolicitResponseOperation";
				}
			}
		}
		#endregion
		
		public ProcessOrchestrationBinding()
		{
		}
		
		public ProcessOrchestrationBinding(Action<IProcessOrchestrationBinding> orchestrationBindingConfigurator)
		{
			orchestrationBindingConfigurator(this);
			((Be.Stateless.BizTalk.Dsl.Binding.ISupportValidation)(this)).Validate();
		}
		
		private ISendPort _SendPort;
		
		ISendPort IProcessOrchestrationBinding.SendPort
		{
			get
			{
				return this._SendPort;
			}
			set
			{
				this._SendPort = value;
			}
		}
		
		private IReceivePort _ReceivePort;
		
		IReceivePort IProcessOrchestrationBinding.ReceivePort
		{
			get
			{
				return this._ReceivePort;
			}
			set
			{
				this._ReceivePort = value;
			}
		}
		
		private IReceivePort _RequestResponsePort;
		
		IReceivePort IProcessOrchestrationBinding.RequestResponsePort
		{
			get
			{
				return this._RequestResponsePort;
			}
			set
			{
				this._RequestResponsePort = value;
			}
		}
		
		private ISendPort _SolicitResponsePort;
		
		ISendPort IProcessOrchestrationBinding.SolicitResponsePort
		{
			get
			{
				return this._SolicitResponsePort;
			}
			set
			{
				this._SolicitResponsePort = value;
			}
		}
	}
}
