//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Be.Stateless.BizTalk.Web.Monitoring.Model", "ProcessProcessingStep", "Process", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Be.Stateless.BizTalk.Web.Monitoring.Model.Process), "ProcessingStep", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Be.Stateless.BizTalk.Web.Monitoring.Model.ProcessingStep), true)]
[assembly: EdmRelationshipAttribute("Be.Stateless.BizTalk.Web.Monitoring.Model", "ProcessProcessMessagingStep", "Process", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Be.Stateless.BizTalk.Web.Monitoring.Model.Process), "ProcessMessagingStep", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Be.Stateless.BizTalk.Web.Monitoring.Model.ProcessMessagingStep), true)]
[assembly: EdmRelationshipAttribute("Be.Stateless.BizTalk.Web.Monitoring.Model", "MessagingStepProcessMessagingStep", "MessagingStep", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Be.Stateless.BizTalk.Web.Monitoring.Model.MessagingStep), "ProcessMessagingStep", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Be.Stateless.BizTalk.Web.Monitoring.Model.ProcessMessagingStep), true)]
[assembly: EdmRelationshipAttribute("Be.Stateless.BizTalk.Web.Monitoring.Model", "MessagingStepContext", "MessagingStep", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Be.Stateless.BizTalk.Web.Monitoring.Model.MessagingStep), "Context", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Be.Stateless.BizTalk.Web.Monitoring.Model.Context), true)]
[assembly: EdmRelationshipAttribute("Be.Stateless.BizTalk.Web.Monitoring.Model", "MessagingStepMessage", "MessagingStep", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Be.Stateless.BizTalk.Web.Monitoring.Model.MessagingStep), "Message", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Be.Stateless.BizTalk.Web.Monitoring.Model.Message), true)]

#endregion

namespace Be.Stateless.BizTalk.Web.Monitoring.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TrackingEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TrackingEntities object using the connection string found in the 'TrackingEntities' section of the application configuration file.
        /// </summary>
        public TrackingEntities() : base("name=TrackingEntities", "TrackingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TrackingEntities object.
        /// </summary>
        public TrackingEntities(string connectionString) : base(connectionString, "TrackingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TrackingEntities object.
        /// </summary>
        public TrackingEntities(EntityConnection connection) : base(connection, "TrackingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Process> Processes
        {
            get
            {
                if ((_Processes == null))
                {
                    _Processes = base.CreateObjectSet<Process>("Processes");
                }
                return _Processes;
            }
        }
        private ObjectSet<Process> _Processes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProcessingStep> ProcessingSteps
        {
            get
            {
                if ((_ProcessingSteps == null))
                {
                    _ProcessingSteps = base.CreateObjectSet<ProcessingStep>("ProcessingSteps");
                }
                return _ProcessingSteps;
            }
        }
        private ObjectSet<ProcessingStep> _ProcessingSteps;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProcessMessagingStep> ProcessMessagingSteps
        {
            get
            {
                if ((_ProcessMessagingSteps == null))
                {
                    _ProcessMessagingSteps = base.CreateObjectSet<ProcessMessagingStep>("ProcessMessagingSteps");
                }
                return _ProcessMessagingSteps;
            }
        }
        private ObjectSet<ProcessMessagingStep> _ProcessMessagingSteps;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MessagingStep> MessagingSteps
        {
            get
            {
                if ((_MessagingSteps == null))
                {
                    _MessagingSteps = base.CreateObjectSet<MessagingStep>("MessagingSteps");
                }
                return _MessagingSteps;
            }
        }
        private ObjectSet<MessagingStep> _MessagingSteps;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Context> Contexts
        {
            get
            {
                if ((_Contexts == null))
                {
                    _Contexts = base.CreateObjectSet<Context>("Contexts");
                }
                return _Contexts;
            }
        }
        private ObjectSet<Context> _Contexts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Message> Messages
        {
            get
            {
                if ((_Messages == null))
                {
                    _Messages = base.CreateObjectSet<Message>("Messages");
                }
                return _Messages;
            }
        }
        private ObjectSet<Message> _Messages;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Processes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProcesses(Process process)
        {
            base.AddObject("Processes", process);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProcessingSteps EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProcessingSteps(ProcessingStep processingStep)
        {
            base.AddObject("ProcessingSteps", processingStep);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProcessMessagingSteps EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProcessMessagingSteps(ProcessMessagingStep processMessagingStep)
        {
            base.AddObject("ProcessMessagingSteps", processMessagingStep);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MessagingSteps EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMessagingSteps(MessagingStep messagingStep)
        {
            base.AddObject("MessagingSteps", messagingStep);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Contexts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToContexts(Context context)
        {
            base.AddObject("Contexts", context);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Messages EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMessages(Message message)
        {
            base.AddObject("Messages", message);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Be.Stateless.BizTalk.Web.Monitoring.Model", Name="Context")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Context : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Context object.
        /// </summary>
        /// <param name="messagingStepActivityID">Initial value of the MessagingStepActivityID property.</param>
        public static Context CreateContext(global::System.String messagingStepActivityID)
        {
            Context context = new Context();
            context.MessagingStepActivityID = messagingStepActivityID;
            return context;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MessagingStepActivityID
        {
            get
            {
                return _MessagingStepActivityID;
            }
            set
            {
                if (_MessagingStepActivityID != value)
                {
                    OnMessagingStepActivityIDChanging(value);
                    ReportPropertyChanging("MessagingStepActivityID");
                    _MessagingStepActivityID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MessagingStepActivityID");
                    OnMessagingStepActivityIDChanged();
                }
            }
        }
        private global::System.String _MessagingStepActivityID;
        partial void OnMessagingStepActivityIDChanging(global::System.String value);
        partial void OnMessagingStepActivityIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EncodedContext
        {
            get
            {
                return _EncodedContext;
            }
            set
            {
                OnEncodedContextChanging(value);
                ReportPropertyChanging("EncodedContext");
                _EncodedContext = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EncodedContext");
                OnEncodedContextChanged();
            }
        }
        private global::System.String _EncodedContext;
        partial void OnEncodedContextChanging(global::System.String value);
        partial void OnEncodedContextChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Be.Stateless.BizTalk.Web.Monitoring.Model", "MessagingStepContext", "MessagingStep")]
        public MessagingStep MessagingStep
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MessagingStep>("Be.Stateless.BizTalk.Web.Monitoring.Model.MessagingStepContext", "MessagingStep").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MessagingStep>("Be.Stateless.BizTalk.Web.Monitoring.Model.MessagingStepContext", "MessagingStep").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MessagingStep> MessagingStepReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MessagingStep>("Be.Stateless.BizTalk.Web.Monitoring.Model.MessagingStepContext", "MessagingStep");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MessagingStep>("Be.Stateless.BizTalk.Web.Monitoring.Model.MessagingStepContext", "MessagingStep", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Be.Stateless.BizTalk.Web.Monitoring.Model", Name="Message")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Message : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Message object.
        /// </summary>
        /// <param name="messagingStepActivityID">Initial value of the MessagingStepActivityID property.</param>
        /// <param name="encodedBodyType">Initial value of the EncodedBodyType property.</param>
        public static Message CreateMessage(global::System.String messagingStepActivityID, global::System.String encodedBodyType)
        {
            Message message = new Message();
            message.MessagingStepActivityID = messagingStepActivityID;
            message.EncodedBodyType = encodedBodyType;
            return message;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MessagingStepActivityID
        {
            get
            {
                return _MessagingStepActivityID;
            }
            set
            {
                if (_MessagingStepActivityID != value)
                {
                    OnMessagingStepActivityIDChanging(value);
                    ReportPropertyChanging("MessagingStepActivityID");
                    _MessagingStepActivityID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MessagingStepActivityID");
                    OnMessagingStepActivityIDChanged();
                }
            }
        }
        private global::System.String _MessagingStepActivityID;
        partial void OnMessagingStepActivityIDChanging(global::System.String value);
        partial void OnMessagingStepActivityIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EncodedBodyType
        {
            get
            {
                return _EncodedBodyType;
            }
            set
            {
                OnEncodedBodyTypeChanging(value);
                ReportPropertyChanging("EncodedBodyType");
                _EncodedBodyType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EncodedBodyType");
                OnEncodedBodyTypeChanged();
            }
        }
        private global::System.String _EncodedBodyType;
        partial void OnEncodedBodyTypeChanging(global::System.String value);
        partial void OnEncodedBodyTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EncodedBody
        {
            get
            {
                return _EncodedBody;
            }
            set
            {
                OnEncodedBodyChanging(value);
                ReportPropertyChanging("EncodedBody");
                _EncodedBody = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EncodedBody");
                OnEncodedBodyChanged();
            }
        }
        private global::System.String _EncodedBody;
        partial void OnEncodedBodyChanging(global::System.String value);
        partial void OnEncodedBodyChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Be.Stateless.BizTalk.Web.Monitoring.Model", "MessagingStepMessage", "MessagingStep")]
        public MessagingStep MessagingStep
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MessagingStep>("Be.Stateless.BizTalk.Web.Monitoring.Model.MessagingStepMessage", "MessagingStep").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MessagingStep>("Be.Stateless.BizTalk.Web.Monitoring.Model.MessagingStepMessage", "MessagingStep").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MessagingStep> MessagingStepReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MessagingStep>("Be.Stateless.BizTalk.Web.Monitoring.Model.MessagingStepMessage", "MessagingStep");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MessagingStep>("Be.Stateless.BizTalk.Web.Monitoring.Model.MessagingStepMessage", "MessagingStep", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Be.Stateless.BizTalk.Web.Monitoring.Model", Name="MessagingStep")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MessagingStep : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MessagingStep object.
        /// </summary>
        /// <param name="activityID">Initial value of the ActivityID property.</param>
        public static MessagingStep CreateMessagingStep(global::System.String activityID)
        {
            MessagingStep messagingStep = new MessagingStep();
            messagingStep.ActivityID = activityID;
            return messagingStep;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> RecordID
        {
            get
            {
                return _RecordID;
            }
            set
            {
                OnRecordIDChanging(value);
                ReportPropertyChanging("RecordID");
                _RecordID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RecordID");
                OnRecordIDChanged();
            }
        }
        private Nullable<global::System.Int64> _RecordID;
        partial void OnRecordIDChanging(Nullable<global::System.Int64> value);
        partial void OnRecordIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ActivityID
        {
            get
            {
                return _ActivityID;
            }
            set
            {
                if (_ActivityID != value)
                {
                    OnActivityIDChanging(value);
                    ReportPropertyChanging("ActivityID");
                    _ActivityID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ActivityID");
                    OnActivityIDChanged();
                }
            }
        }
        private global::System.String _ActivityID;
        partial void OnActivityIDChanging(global::System.String value);
        partial void OnActivityIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> BeginTime
        {
            get
            {
                return _BeginTime;
            }
            set
            {
                OnBeginTimeChanging(value);
                ReportPropertyChanging("BeginTime");
                _BeginTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BeginTime");
                OnBeginTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _BeginTime;
        partial void OnBeginTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnBeginTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EndTime
        {
            get
            {
                return _EndTime;
            }
            set
            {
                OnEndTimeChanging(value);
                ReportPropertyChanging("EndTime");
                _EndTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndTime");
                OnEndTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _EndTime;
        partial void OnEndTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnEndTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ErrorCode
        {
            get
            {
                return _ErrorCode;
            }
            set
            {
                OnErrorCodeChanging(value);
                ReportPropertyChanging("ErrorCode");
                _ErrorCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ErrorCode");
                OnErrorCodeChanged();
            }
        }
        private global::System.String _ErrorCode;
        partial void OnErrorCodeChanging(global::System.String value);
        partial void OnErrorCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ErrorDescription
        {
            get
            {
                return _ErrorDescription;
            }
            set
            {
                OnErrorDescriptionChanging(value);
                ReportPropertyChanging("ErrorDescription");
                _ErrorDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ErrorDescription");
                OnErrorDescriptionChanged();
            }
        }
        private global::System.String _ErrorDescription;
        partial void OnErrorDescriptionChanging(global::System.String value);
        partial void OnErrorDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String InterchangeID
        {
            get
            {
                return _InterchangeID;
            }
            set
            {
                OnInterchangeIDChanging(value);
                ReportPropertyChanging("InterchangeID");
                _InterchangeID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("InterchangeID");
                OnInterchangeIDChanged();
            }
        }
        private global::System.String _InterchangeID;
        partial void OnInterchangeIDChanging(global::System.String value);
        partial void OnInterchangeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Key1
        {
            get
            {
                return _Key1;
            }
            set
            {
                OnKey1Changing(value);
                ReportPropertyChanging("Key1");
                _Key1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Key1");
                OnKey1Changed();
            }
        }
        private global::System.String _Key1;
        partial void OnKey1Changing(global::System.String value);
        partial void OnKey1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Key2
        {
            get
            {
                return _Key2;
            }
            set
            {
                OnKey2Changing(value);
                ReportPropertyChanging("Key2");
                _Key2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Key2");
                OnKey2Changed();
            }
        }
        private global::System.String _Key2;
        partial void OnKey2Changing(global::System.String value);
        partial void OnKey2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Key3
        {
            get
            {
                return _Key3;
            }
            set
            {
                OnKey3Changing(value);
                ReportPropertyChanging("Key3");
                _Key3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Key3");
                OnKey3Changed();
            }
        }
        private global::System.String _Key3;
        partial void OnKey3Changing(global::System.String value);
        partial void OnKey3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MachineName
        {
            get
            {
                return _MachineName;
            }
            set
            {
                OnMachineNameChanging(value);
                ReportPropertyChanging("MachineName");
                _MachineName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MachineName");
                OnMachineNameChanged();
            }
        }
        private global::System.String _MachineName;
        partial void OnMachineNameChanging(global::System.String value);
        partial void OnMachineNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MessageID
        {
            get
            {
                return _MessageID;
            }
            set
            {
                OnMessageIDChanging(value);
                ReportPropertyChanging("MessageID");
                _MessageID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MessageID");
                OnMessageIDChanged();
            }
        }
        private global::System.String _MessageID;
        partial void OnMessageIDChanging(global::System.String value);
        partial void OnMessageIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MessageSize
        {
            get
            {
                return _MessageSize;
            }
            set
            {
                OnMessageSizeChanging(value);
                ReportPropertyChanging("MessageSize");
                _MessageSize = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MessageSize");
                OnMessageSizeChanged();
            }
        }
        private Nullable<global::System.Int32> _MessageSize;
        partial void OnMessageSizeChanging(Nullable<global::System.Int32> value);
        partial void OnMessageSizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MessageType
        {
            get
            {
                return _MessageType;
            }
            set
            {
                OnMessageTypeChanging(value);
                ReportPropertyChanging("MessageType");
                _MessageType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MessageType");
                OnMessageTypeChanged();
            }
        }
        private global::System.String _MessageType;
        partial void OnMessageTypeChanging(global::System.String value);
        partial void OnMessageTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RetryCount
        {
            get
            {
                return _RetryCount;
            }
            set
            {
                OnRetryCountChanging(value);
                ReportPropertyChanging("RetryCount");
                _RetryCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RetryCount");
                OnRetryCountChanged();
            }
        }
        private Nullable<global::System.Int32> _RetryCount;
        partial void OnRetryCountChanging(Nullable<global::System.Int32> value);
        partial void OnRetryCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TransportLocation
        {
            get
            {
                return _TransportLocation;
            }
            set
            {
                OnTransportLocationChanging(value);
                ReportPropertyChanging("TransportLocation");
                _TransportLocation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TransportLocation");
                OnTransportLocationChanged();
            }
        }
        private global::System.String _TransportLocation;
        partial void OnTransportLocationChanging(global::System.String value);
        partial void OnTransportLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TransportType
        {
            get
            {
                return _TransportType;
            }
            set
            {
                OnTransportTypeChanging(value);
                ReportPropertyChanging("TransportType");
                _TransportType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TransportType");
                OnTransportTypeChanged();
            }
        }
        private global::System.String _TransportType;
        partial void OnTransportTypeChanging(global::System.String value);
        partial void OnTransportTypeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Be.Stateless.BizTalk.Web.Monitoring.Model", "MessagingStepProcessMessagingStep", "ProcessMessagingStep")]
        public EntityCollection<ProcessMessagingStep> RelatedProcesses
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ProcessMessagingStep>("Be.Stateless.BizTalk.Web.Monitoring.Model.MessagingStepProcessMessagingStep", "ProcessMessagingStep");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ProcessMessagingStep>("Be.Stateless.BizTalk.Web.Monitoring.Model.MessagingStepProcessMessagingStep", "ProcessMessagingStep", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Be.Stateless.BizTalk.Web.Monitoring.Model", "MessagingStepContext", "Context")]
        public Context RawContext
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Context>("Be.Stateless.BizTalk.Web.Monitoring.Model.MessagingStepContext", "Context").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Context>("Be.Stateless.BizTalk.Web.Monitoring.Model.MessagingStepContext", "Context").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Context> RawContextReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Context>("Be.Stateless.BizTalk.Web.Monitoring.Model.MessagingStepContext", "Context");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Context>("Be.Stateless.BizTalk.Web.Monitoring.Model.MessagingStepContext", "Context", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Be.Stateless.BizTalk.Web.Monitoring.Model", "MessagingStepMessage", "Message")]
        public Message RawMessage
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Message>("Be.Stateless.BizTalk.Web.Monitoring.Model.MessagingStepMessage", "Message").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Message>("Be.Stateless.BizTalk.Web.Monitoring.Model.MessagingStepMessage", "Message").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Message> RawMessageReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Message>("Be.Stateless.BizTalk.Web.Monitoring.Model.MessagingStepMessage", "Message");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Message>("Be.Stateless.BizTalk.Web.Monitoring.Model.MessagingStepMessage", "Message", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Be.Stateless.BizTalk.Web.Monitoring.Model", Name="Process")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Process : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Process object.
        /// </summary>
        /// <param name="activityID">Initial value of the ActivityID property.</param>
        public static Process CreateProcess(global::System.String activityID)
        {
            Process process = new Process();
            process.ActivityID = activityID;
            return process;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> RecordID
        {
            get
            {
                return _RecordID;
            }
            set
            {
                OnRecordIDChanging(value);
                ReportPropertyChanging("RecordID");
                _RecordID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RecordID");
                OnRecordIDChanged();
            }
        }
        private Nullable<global::System.Int64> _RecordID;
        partial void OnRecordIDChanging(Nullable<global::System.Int64> value);
        partial void OnRecordIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ActivityID
        {
            get
            {
                return _ActivityID;
            }
            set
            {
                if (_ActivityID != value)
                {
                    OnActivityIDChanging(value);
                    ReportPropertyChanging("ActivityID");
                    _ActivityID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ActivityID");
                    OnActivityIDChanged();
                }
            }
        }
        private global::System.String _ActivityID;
        partial void OnActivityIDChanging(global::System.String value);
        partial void OnActivityIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> BeginTime
        {
            get
            {
                return _BeginTime;
            }
            set
            {
                OnBeginTimeChanging(value);
                ReportPropertyChanging("BeginTime");
                _BeginTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BeginTime");
                OnBeginTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _BeginTime;
        partial void OnBeginTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnBeginTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EndTime
        {
            get
            {
                return _EndTime;
            }
            set
            {
                OnEndTimeChanging(value);
                ReportPropertyChanging("EndTime");
                _EndTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndTime");
                OnEndTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _EndTime;
        partial void OnEndTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnEndTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Key1
        {
            get
            {
                return _Key1;
            }
            set
            {
                OnKey1Changing(value);
                ReportPropertyChanging("Key1");
                _Key1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Key1");
                OnKey1Changed();
            }
        }
        private global::System.String _Key1;
        partial void OnKey1Changing(global::System.String value);
        partial void OnKey1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Key2
        {
            get
            {
                return _Key2;
            }
            set
            {
                OnKey2Changing(value);
                ReportPropertyChanging("Key2");
                _Key2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Key2");
                OnKey2Changed();
            }
        }
        private global::System.String _Key2;
        partial void OnKey2Changing(global::System.String value);
        partial void OnKey2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Key3
        {
            get
            {
                return _Key3;
            }
            set
            {
                OnKey3Changing(value);
                ReportPropertyChanging("Key3");
                _Key3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Key3");
                OnKey3Changed();
            }
        }
        private global::System.String _Key3;
        partial void OnKey3Changing(global::System.String value);
        partial void OnKey3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Be.Stateless.BizTalk.Web.Monitoring.Model", "ProcessProcessingStep", "ProcessingStep")]
        public EntityCollection<ProcessingStep> ProcessingSteps
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ProcessingStep>("Be.Stateless.BizTalk.Web.Monitoring.Model.ProcessProcessingStep", "ProcessingStep");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ProcessingStep>("Be.Stateless.BizTalk.Web.Monitoring.Model.ProcessProcessingStep", "ProcessingStep", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Be.Stateless.BizTalk.Web.Monitoring.Model", "ProcessProcessMessagingStep", "ProcessMessagingStep")]
        public EntityCollection<ProcessMessagingStep> RelatedMessagingSteps
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ProcessMessagingStep>("Be.Stateless.BizTalk.Web.Monitoring.Model.ProcessProcessMessagingStep", "ProcessMessagingStep");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ProcessMessagingStep>("Be.Stateless.BizTalk.Web.Monitoring.Model.ProcessProcessMessagingStep", "ProcessMessagingStep", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Be.Stateless.BizTalk.Web.Monitoring.Model", Name="ProcessingStep")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProcessingStep : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProcessingStep object.
        /// </summary>
        /// <param name="activityID">Initial value of the ActivityID property.</param>
        /// <param name="processActivityID">Initial value of the ProcessActivityID property.</param>
        public static ProcessingStep CreateProcessingStep(global::System.String activityID, global::System.String processActivityID)
        {
            ProcessingStep processingStep = new ProcessingStep();
            processingStep.ActivityID = activityID;
            processingStep.ProcessActivityID = processActivityID;
            return processingStep;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> RecordID
        {
            get
            {
                return _RecordID;
            }
            set
            {
                OnRecordIDChanging(value);
                ReportPropertyChanging("RecordID");
                _RecordID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RecordID");
                OnRecordIDChanged();
            }
        }
        private Nullable<global::System.Int64> _RecordID;
        partial void OnRecordIDChanging(Nullable<global::System.Int64> value);
        partial void OnRecordIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ActivityID
        {
            get
            {
                return _ActivityID;
            }
            set
            {
                if (_ActivityID != value)
                {
                    OnActivityIDChanging(value);
                    ReportPropertyChanging("ActivityID");
                    _ActivityID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ActivityID");
                    OnActivityIDChanged();
                }
            }
        }
        private global::System.String _ActivityID;
        partial void OnActivityIDChanging(global::System.String value);
        partial void OnActivityIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> BeginTime
        {
            get
            {
                return _BeginTime;
            }
            set
            {
                OnBeginTimeChanging(value);
                ReportPropertyChanging("BeginTime");
                _BeginTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BeginTime");
                OnBeginTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _BeginTime;
        partial void OnBeginTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnBeginTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EndTime
        {
            get
            {
                return _EndTime;
            }
            set
            {
                OnEndTimeChanging(value);
                ReportPropertyChanging("EndTime");
                _EndTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndTime");
                OnEndTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _EndTime;
        partial void OnEndTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnEndTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ErrorDescription
        {
            get
            {
                return _ErrorDescription;
            }
            set
            {
                OnErrorDescriptionChanging(value);
                ReportPropertyChanging("ErrorDescription");
                _ErrorDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ErrorDescription");
                OnErrorDescriptionChanged();
            }
        }
        private global::System.String _ErrorDescription;
        partial void OnErrorDescriptionChanging(global::System.String value);
        partial void OnErrorDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MachineName
        {
            get
            {
                return _MachineName;
            }
            set
            {
                OnMachineNameChanging(value);
                ReportPropertyChanging("MachineName");
                _MachineName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MachineName");
                OnMachineNameChanged();
            }
        }
        private global::System.String _MachineName;
        partial void OnMachineNameChanging(global::System.String value);
        partial void OnMachineNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProcessActivityID
        {
            get
            {
                return _ProcessActivityID;
            }
            set
            {
                OnProcessActivityIDChanging(value);
                ReportPropertyChanging("ProcessActivityID");
                _ProcessActivityID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ProcessActivityID");
                OnProcessActivityIDChanged();
            }
        }
        private global::System.String _ProcessActivityID;
        partial void OnProcessActivityIDChanging(global::System.String value);
        partial void OnProcessActivityIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Be.Stateless.BizTalk.Web.Monitoring.Model", "ProcessProcessingStep", "Process")]
        public Process Process
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Process>("Be.Stateless.BizTalk.Web.Monitoring.Model.ProcessProcessingStep", "Process").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Process>("Be.Stateless.BizTalk.Web.Monitoring.Model.ProcessProcessingStep", "Process").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Process> ProcessReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Process>("Be.Stateless.BizTalk.Web.Monitoring.Model.ProcessProcessingStep", "Process");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Process>("Be.Stateless.BizTalk.Web.Monitoring.Model.ProcessProcessingStep", "Process", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Be.Stateless.BizTalk.Web.Monitoring.Model", Name="ProcessMessagingStep")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProcessMessagingStep : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProcessMessagingStep object.
        /// </summary>
        /// <param name="activityID">Initial value of the ActivityID property.</param>
        /// <param name="messagingStepActivityID">Initial value of the MessagingStepActivityID property.</param>
        /// <param name="processActivityID">Initial value of the ProcessActivityID property.</param>
        public static ProcessMessagingStep CreateProcessMessagingStep(global::System.String activityID, global::System.String messagingStepActivityID, global::System.String processActivityID)
        {
            ProcessMessagingStep processMessagingStep = new ProcessMessagingStep();
            processMessagingStep.ActivityID = activityID;
            processMessagingStep.MessagingStepActivityID = messagingStepActivityID;
            processMessagingStep.ProcessActivityID = processActivityID;
            return processMessagingStep;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> RecordID
        {
            get
            {
                return _RecordID;
            }
            set
            {
                OnRecordIDChanging(value);
                ReportPropertyChanging("RecordID");
                _RecordID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RecordID");
                OnRecordIDChanged();
            }
        }
        private Nullable<global::System.Int64> _RecordID;
        partial void OnRecordIDChanging(Nullable<global::System.Int64> value);
        partial void OnRecordIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ActivityID
        {
            get
            {
                return _ActivityID;
            }
            set
            {
                if (_ActivityID != value)
                {
                    OnActivityIDChanging(value);
                    ReportPropertyChanging("ActivityID");
                    _ActivityID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ActivityID");
                    OnActivityIDChanged();
                }
            }
        }
        private global::System.String _ActivityID;
        partial void OnActivityIDChanging(global::System.String value);
        partial void OnActivityIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MessagingStepActivityID
        {
            get
            {
                return _MessagingStepActivityID;
            }
            set
            {
                OnMessagingStepActivityIDChanging(value);
                ReportPropertyChanging("MessagingStepActivityID");
                _MessagingStepActivityID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MessagingStepActivityID");
                OnMessagingStepActivityIDChanged();
            }
        }
        private global::System.String _MessagingStepActivityID;
        partial void OnMessagingStepActivityIDChanging(global::System.String value);
        partial void OnMessagingStepActivityIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MessagingStepStatus
        {
            get
            {
                return _MessagingStepStatus;
            }
            set
            {
                OnMessagingStepStatusChanging(value);
                ReportPropertyChanging("MessagingStepStatus");
                _MessagingStepStatus = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MessagingStepStatus");
                OnMessagingStepStatusChanged();
            }
        }
        private global::System.String _MessagingStepStatus;
        partial void OnMessagingStepStatusChanging(global::System.String value);
        partial void OnMessagingStepStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProcessActivityID
        {
            get
            {
                return _ProcessActivityID;
            }
            set
            {
                OnProcessActivityIDChanging(value);
                ReportPropertyChanging("ProcessActivityID");
                _ProcessActivityID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ProcessActivityID");
                OnProcessActivityIDChanged();
            }
        }
        private global::System.String _ProcessActivityID;
        partial void OnProcessActivityIDChanging(global::System.String value);
        partial void OnProcessActivityIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Be.Stateless.BizTalk.Web.Monitoring.Model", "ProcessProcessMessagingStep", "Process")]
        public Process Process
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Process>("Be.Stateless.BizTalk.Web.Monitoring.Model.ProcessProcessMessagingStep", "Process").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Process>("Be.Stateless.BizTalk.Web.Monitoring.Model.ProcessProcessMessagingStep", "Process").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Process> ProcessReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Process>("Be.Stateless.BizTalk.Web.Monitoring.Model.ProcessProcessMessagingStep", "Process");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Process>("Be.Stateless.BizTalk.Web.Monitoring.Model.ProcessProcessMessagingStep", "Process", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Be.Stateless.BizTalk.Web.Monitoring.Model", "MessagingStepProcessMessagingStep", "MessagingStep")]
        public MessagingStep MessagingStep
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MessagingStep>("Be.Stateless.BizTalk.Web.Monitoring.Model.MessagingStepProcessMessagingStep", "MessagingStep").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MessagingStep>("Be.Stateless.BizTalk.Web.Monitoring.Model.MessagingStepProcessMessagingStep", "MessagingStep").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MessagingStep> MessagingStepReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MessagingStep>("Be.Stateless.BizTalk.Web.Monitoring.Model.MessagingStepProcessMessagingStep", "MessagingStep");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MessagingStep>("Be.Stateless.BizTalk.Web.Monitoring.Model.MessagingStepProcessMessagingStep", "MessagingStep", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
