//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Be.Stateless.BizTalk.Orchestrations.Direct
{
	using System;
	using System.CodeDom.Compiler;
	using Be.Stateless.BizTalk.Dsl.Binding;
	using Microsoft.XLANGs.Core;
	using Be.Stateless.BizTalk.Orchestrations.Direct;
	
	
	[GeneratedCodeAttribute("Be.Stateless.BizTalk.Dsl", "1.0.0.0")]
	internal partial class ProcessOrchestrationBinding : OrchestrationBindingBase<Process>
	{
		
		#region Nested Type: DirectReceivePort
		public struct DirectReceivePort
		{
			
			public struct Operations
			{
				
				public struct Receive
				{
					
					public static string Name = "Receive";
				}
			}
		}
		#endregion
		
		#region Nested Type: DirectSendPort
		public struct DirectSendPort
		{
			
			public struct Operations
			{
				
				public struct Operation
				{
					
					public static string Name = "Operation";
				}
			}
		}
		#endregion
		
		public ProcessOrchestrationBinding()
		{
		}
		
		public ProcessOrchestrationBinding(Action<ProcessOrchestrationBinding> orchestrationBindingConfigurator)
		{
			orchestrationBindingConfigurator(this);
			((Be.Stateless.BizTalk.Dsl.Binding.ISupportValidation)(this)).Validate();
		}
	}
}
